"""changed column structure of products and added a brands model

Revision ID: 9917d9bc0021
Revises: c98d92cf6f7d
Create Date: 2024-10-28 10:30:05.329859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9917d9bc0021'
down_revision: Union[str, None] = 'c98d92cf6f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('videos')
    op.drop_table('apple_ceos')
    op.drop_table('houses')
    op.drop_table('answers')
    op.drop_table('students')
    op.drop_index('ix_pigs_id', table_name='pigs')
    op.drop_table('pigs')
    op.drop_table('courses')
    op.drop_table('enrollments')
    op.drop_table('rankings')
    op.drop_index('ix_wolves_id', table_name='wolves')
    op.drop_table('wolves')
    op.drop_table('topics')
    op.drop_table('skaters')
    op.drop_table('pictures')
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'brand_id')
    op.create_table('pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skater_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skater_picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skater_id'], ['skaters.id'], name='pictures_skater_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pictures_pkey')
    )
    op.create_table('skaters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skaters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('skater_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='skaters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='topics_pkey')
    )
    op.create_table('wolves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wolf_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wolf_power', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wolves_pkey')
    )
    op.create_index('ix_wolves_id', 'wolves', ['id'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ranking_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ranking_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rankings_pkey')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enrollment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='enrollments_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='enrollments_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='enrollments_pkey')
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='courses_pkey')
    )
    op.create_table('pigs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pigs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pig_house', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pig_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pigs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_pigs_id', 'pigs', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    op.create_table('houses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('house_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('house_sturdiness', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pig_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pig_id'], ['pigs.id'], name='houses_pig_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='houses_pkey')
    )
    op.create_table('apple_ceos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('first_year_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='apple_ceos_pkey')
    )
    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skater_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('youtube_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('video_date >= 1000 AND video_date <= 9999', name='videos_video_date_check'),
    sa.ForeignKeyConstraint(['skater_id'], ['skaters.id'], name='videos_skater_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='videos_pkey')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='questions_pkey')
    )
    # ### end Alembic commands ###
